djangoProject01/urls.py
from django.urls import path, re_path
from django.views.static import serve
from django.conf import settings
from app01.views import depart, user, pretty, admin, account, city, avatar, task, order, chart

urlpatterns = [
    # 默认访问用户列表页面
    path('', user.user_list),

    # 部门管理
    path('depart/list/', depart.depart_list),
    path('depart/add/', depart.depart_add),
    path('depart/<int:nid>/delete/', depart.depart_delete),
    path('depart/<int:nid>/edit/', depart.depart_edit),

    # # 用户管理
    # path('user/list/', user.user_list),
    # path('user/add/', user.user_add),
    # path('user/<int:nid>/edit/', user.user_edit),
    # path('user/<int:nid>/delete/', user.user_delete),
    #
    # # 靓号管理
    # path('pretty/list/', pretty.pretty_list),
    # path('pretty/add/', pretty.pretty_add),
    # path('pretty/<int:nid>/edit/', pretty.pretty_edit),
    # path('pretty/<int:nid>/delete/', pretty.pretty_delete),
    #
    # 管理员管理
    path('admin/list/', admin.admin_list),
    path('admin/add/', admin.admin_add),
    path('admin/<int:nid>/edit/', admin.admin_edit),
    path('admin/<int:nid>/delete/', admin.admin_delete),
    path('admin/<int:nid>/reset/', admin.admin_reset),

    # 登录
    path('login/', account.login),
    path('logout/', account.logout),
    path('image/code/', account.image_code),

    # 注册
    path('register/', account.register),

    # 上传图片
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),

    # # 城市列表
    # path('city/list/', city.city_list),
    # path('city/add/', city.city_add),
    #
    # # 头像
    # path('avatar/edit/', avatar.avatar_edit),
    #
    # # 任务管理
    # path('task/list/', task.task_list),
    # path('task/add/', task.task_add),
    #
    # # 订单管理
    # path('order/list/', order.order_list),
    # path('order/add/', order.order_add),
    # path('order/delete/', order.order_delete),
    # path('order/detail/', order.order_detail),
    # path('order/edit/', order.order_edit),
    #
    # # 数据统计
    # path('chart/list/', chart.chart_list),
    # path('chart/bar/', chart.chart_bar),
    # path('chart/pie/', chart.chart_pie),
    # path('chart/line/', chart.chart_line),
    # path('chart/highcharts/', chart.chart_highcharts),


]

app01/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


class Admin(models.Model):
    """管理员表"""
    username = models.CharField(verbose_name='用户名', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=64)# 在Django中做的约束

    poole_level_choices = (
        (1, '管理员'),  # 1 represents the stored value in the database
        (2, '用户'),  # 2 represents the stored value in the database
    )
    level = models.SmallIntegerField(verbose_name='等级', choices=poole_level_choices, default=2)


    def __str__(self):
        return self.username


class Department(models.Model):
    """部门表"""
    title = models.CharField(verbose_name='标题', max_length=256)
    guige = models.CharField(verbose_name='规格', max_length=256, blank=True, null=True)
    price = models.DecimalField(verbose_name="综合单价", max_digits=10, decimal_places=2, blank=True, null=True)
    hd_name = models.CharField(max_length=1000, verbose_name="活动名称", blank=True, null=True)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class UserInfo(models.Model):
    """员工表"""
    name = models.CharField(verbose_name='姓名', max_length=16)
    password = models.CharField(verbose_name='密码', max_length=64)
    age = models.IntegerField(verbose_name='年龄')
    account = models.DecimalField(verbose_name='账户余额', max_digits=10, decimal_places=2, default=0)
    # create_time = models.DateTimeField(verbose_name='入职时间')
    create_time = models.DateField(verbose_name='入职时间')

    # 无约束
    # depart_id = models.BigIntegerField(verbose_name='部门id')

    # 1.有约束
    #   -to,与那张表关联
    #   -to_field,表中的那一列关联
    # 2.Django自动
    #   -写的depart
    #   -生成数据列 depart_id
    # 3.部门表被删除
    #  3.1 级联删除  on_delete=models.CASCADE  表示如果部门表被删除，旗下的部门表的员工也被删除
    depart = models.ForeignKey(verbose_name='部门', to='Department', to_field='id', on_delete=models.CASCADE)
    #  3.2 置空  null=True, blank=True, on_delete=models.SET_NULL 表示如果部门表被删除，旗下的部门表的员工部门位为空值
    # depart = models.ForeignKey(to='Department', to_field='id', null=True, blank=True, on_delete=models.SET_NULL)

    # 在Django中做的约束
    gender_choices = (
        (1, '男'),
        (2, '女'),
    )
    gender = models.SmallIntegerField(verbose_name='性别', choices=gender_choices)


class PrettyNum(models.Model):
    """靓号表"""
    mobile = models.CharField(verbose_name="手机号", max_length=11)
    price = models.IntegerField(verbose_name="价格", default=0)

    level_choices = (
        (1, '1级'),
        (2, '2级'),
        (3, '3级'),
        (4, '4级'),
    )

    level = models.SmallIntegerField(verbose_name="级别", choices=level_choices, default=1)

    status_choices = (
        (1, '已使用'),
        (2, '未使用'),
    )

    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=2)


class City(models.Model):
    """城市表"""
    name = models.CharField(verbose_name='名称', max_length=32)
    count = models.IntegerField(verbose_name='人口')

    img = models.FileField(verbose_name='Logo', max_length=128, upload_to='city/')


class Task(models.Model):
    """ 任务 """
    level_choices = (
        (1, '紧急'),
        (2, '重要'),
        (3, '临时'),
    )

    level = models.SmallIntegerField(verbose_name='级别', choices=level_choices, default=1)
    title = models.CharField(verbose_name='标题', max_length=64)
    detail = models.TextField(verbose_name='详细信息')
    user = models.ForeignKey(verbose_name='负责人', to='Admin', to_field='id', on_delete=models.CASCADE)


class Order(models.Model):
    """订单"""
    oid = models.CharField(verbose_name="订单号", max_length=64)
    title = models.CharField(verbose_name="名称", max_length=32)
    price = models.IntegerField(verbose_name="价格")

    status_choices = (
        (1, '待支付'),
        (2, '已支付'),
    )
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=1)
    admin = models.ForeignKey(verbose_name="管理员", to="Admin", on_delete=models.CASCADE)

app01/views/1.py
from django.shortcuts import render, redirect, get_object_or_404
from app01 import models
from app01.utils.pagination import Pagination
from app01.utils.form import AdminModelForm, AdminEditModelForm, AdminResetModelForm
from django.contrib.sessions.models import Session
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test

def admin_list(request):
    """管理员列表"""
    search_data = request.GET.get('q', '')
    queryset = models.Admin.objects.filter(username__contains=search_data) if search_data else models.Admin.objects.all()

    page_object = Pagination(request, queryset)
    context = {
        'queryset': page_object.page_queryset,
        'page_string': page_object.html(),
        'search_data': search_data,
    }
    return render(request, 'admin_list.html', context)


def admin_add(request):
    """添加管理员"""
    title = '新建管理员'
    if request.method == 'POST':
        form = AdminModelForm(request.POST)
        if form.is_valid():
            if models.Admin.objects.filter(username=form.cleaned_data['username']).exists():
                form.add_error('username', '用户已存在')
            else:
                form.save()
                return redirect('/admin/list/')
    else:
        form = AdminModelForm()

    return render(request, 'change.html', {'form': form, 'title': title})


def get_user_level(request):
    session_id = request.session.session_key
    session = get_object_or_404(Session, session_key=session_id)
    user_id = session.get_decoded().get('info')['id']
    user = get_object_or_404(models.Admin, pk=user_id)
    return user.level


def admin_edit(request, nid):
    """编辑管理员"""
    row_object = get_object_or_404(models.Admin, id=nid)

    if get_user_level(request) != 1:
        messages.error(request, '非管理员，权限不足')
        return redirect('/admin/list/')

    title = '编辑管理员'
    if request.method == 'POST':
        form = AdminEditModelForm(request.POST, instance=row_object)
        if form.is_valid():
            if models.Admin.objects.filter(username=form.cleaned_data['username']).exclude(id=nid).exists():
                form.add_error('username', '用户已存在')
            else:
                form.save()
                return redirect('/admin/list/')
    else:
        form = AdminEditModelForm(instance=row_object)

    return render(request, 'change.html', {'form': form, 'title': title})


def admin_delete(request, nid):
    """删除管理员"""
    if get_user_level(request) != 1:
        messages.error(request, '非管理员，权限不足')
        return redirect('/admin/list/')

    row_object = get_object_or_404(models.Admin, id=nid)
    row_object.delete()
    return redirect('/admin/list/')

app01/views/account.py
# 开发时间 2022/9/13 19:31
# 文件: account.py
"""
管理员 登录 注册 视图
"""
import os
import sys

# 获取当前脚本文件的目录路径
current_dir = os.path.dirname(os.path.realpath(__file__))

# 获取当前目录的祖父目录的路径
grandparent_dir = os.path.abspath(os.path.join(current_dir, '..', '..'))

# 将祖父目录添加到系统路径中，以便Python解释器可以搜索到其中的模块
sys.path.append(grandparent_dir)


from django.shortcuts import render, redirect, HttpResponse
from app01.utils.form import LoginForm, AdminModelForm
from app01 import models
from app01.utils.my_code import check_code
from io import BytesIO


def login(request):
    """登录"""
    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'login.html', {'form': form})

    form = LoginForm(data=request.POST)
    if form.is_valid():
        # 验证码的校验
        user_input_code = form.cleaned_data.pop('code') # 用于获取表单中名为 'code' 的字段的值，并将其从表单数据中移除
        code = request.session.get('image_code', '')
        if code.upper() != user_input_code.upper():
            form.add_error('code', '验证码错误')
            return render(request, 'login.html', {'form': form})

        # 去数据库校验用户名和密码是否正确，获取用户对象 / None
        admin_object = models.Admin.objects.filter(**form.cleaned_data).first()

        if not admin_object:
            form.add_error('password', '用户名或密码错误')
            return render(request, 'login.html', {'form': form})

        # 用户名和密码正确
        # 网站生成随机字符串; 写到用户浏览器的cookie中；在写入到session中；
        request.session['info'] = {'id': admin_object.id, 'name': admin_object.username}

        # session可以保存7天
        request.session.set_expiry(60 * 60 * 24 * 7)

        return redirect('/admin/list/')

    return render(request, 'login.html', {'form': form})


def image_code(request):
    """生成图片验证码"""

    # 调用pillow函数，生成图片
    img, code_string = check_code()

    # 写入到自己的session中（以便后续获取验证码再进行校验）
    request.session['image_code'] = code_string

    # 给session设置60s超时
    request.session.set_expiry(60)

    # 把图片写入到内存中
    stream = BytesIO()
    img.save(stream, 'png')

    return HttpResponse(stream.getvalue())


def logout(request):
    """注销"""
    request.session.clear()
    return redirect('/login/')


def register(request):
    """注册（添加管理员）"""

    if request.method == 'GET':
        form = AdminModelForm()
        return render(request, 'register.html', {'form': form})

    form = AdminModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/login/')
    return render(request, 'register.html', {'form': form})

app01/views/admin.py
# 开发时间 2022/9/13 11:08
# 文件: admin.py
"""
管理员 视图
"""
from django.shortcuts import render, redirect, get_object_or_404
from app01 import models
from app01.utils.pagination import Pagination
from app01.utils.form import AdminModelForm, AdminEditModelForm, AdminResetModelForm
from django.contrib.sessions.models import Session
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test

def admin_list(request):
    """管理员列表"""
    search_data = request.GET.get('q', '')
    queryset = models.Admin.objects.filter(username__contains=search_data) if search_data else models.Admin.objects.all()

    page_object = Pagination(request, queryset)
    context = {
        'queryset': page_object.page_queryset,
        'page_string': page_object.html(),
        'search_data': search_data,
    }
    return render(request, 'admin_list.html', context)


def admin_add(request):
    """添加管理员"""
    if get_user_level(request) != 1:
        messages.error(request, '非管理员，权限不足')
        return redirect('/admin/list/')
    title = '新建管理员'
    if request.method == 'POST':
        form = AdminModelForm(request.POST)
        if form.is_valid():
            if models.Admin.objects.filter(username=form.cleaned_data['username']).exists():
                form.add_error('username', '用户已存在')
            else:
                form.save()
                return redirect('/admin/list/')
    else:
        form = AdminModelForm()

    return render(request, 'change.html', {'form': form, 'title': title})


def get_user_level(request):
    session_id = request.session.session_key
    session = get_object_or_404(Session, session_key=session_id)
    user_id = session.get_decoded().get('info')['id']
    user = get_object_or_404(models.Admin, pk=user_id)
    return user.level


def admin_edit(request, nid):
    """编辑管理员"""
    row_object = get_object_or_404(models.Admin, id=nid)

    if get_user_level(request) != 1:
        messages.error(request, '非管理员，权限不足')
        return redirect('/admin/list/')

    title = '编辑管理员'
    if request.method == 'POST':
        form = AdminEditModelForm(request.POST, instance=row_object)
        if form.is_valid():
            if models.Admin.objects.filter(username=form.cleaned_data['username']).exclude(id=nid).exists():
                form.add_error('username', '用户已存在')
            else:
                form.save()
                return redirect('/admin/list/')
    else:
        form = AdminEditModelForm(instance=row_object)

    return render(request, 'change.html', {'form': form, 'title': title})


def admin_delete(request, nid):
    """删除管理员"""
    if get_user_level(request) != 1:
        messages.error(request, '非管理员，权限不足')
        return redirect('/admin/list/')

    row_object = get_object_or_404(models.Admin, id=nid)
    row_object.delete()
    return redirect('/admin/list/')


def admin_reset(request, nid):
    """重置管理员密码"""
    # 对象 / None
    user_level = get_user_level(request)
    if user_level != 1:
        messages.error(request, '非管理员，权限不足')
        return redirect('/admin/list/')

    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:
        return render(request, 'error.html', {'msg': '数据不存在'})

    title = "重置密码 - {}".format(row_object.username)

    if request.method == 'GET':
        form = AdminResetModelForm()
        return render(request, 'change.html', {'form': form, 'title': title})

    form = AdminResetModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    return render(request, 'change.html', {'form': form, 'title': title})

app01/views/avatar.py
# 开发时间 2022/9/14 21:25
# 文件: avatar.py
from django.shortcuts import render, redirect
"""
更改头像 视图函数
"""


def avatar_edit(request):
    """更改头像"""
    if request.method == 'GET':
        return render(request, 'avatar_edit.html')

    file = request.FILES.get('avatar')
    file_name = 'media/avatar/'+file.name

    with open(file_name, 'wb+') as fo:
        for chunk in file.chunks():
            fo.write(chunk)

    # 将用户头像写到session
    info = request.session.get('info')
    request.session['info'] = {
        'id': info['id'],
        'name': info['name'],
        'avatar': '/'+file_name,
    }

    return redirect('/city/list/')

app01/views/chart.py
# 开发时间 2022/11/1 9:52
# 当前文件: chart.py

from django.shortcuts import render
from django.http import JsonResponse


def chart_list(request):
    """数据统计页面"""
    return render(request, "chart_list.html")


def chart_bar(request):
    """ 构造柱状图的数据"""
    # 数据可以去数据库中获取
    legend = ["萧炎", "美杜莎"]

    series_list = [
        {
            "name": '萧炎',
            "type": 'bar',
            "data": [15, 20, 36, 10, 10, 100]
        },
        {
            "name": '美杜莎',
            "type": 'bar',
            "data": [30, 40, 66, 20, 20, 100]
        }
    ]

    x_axis = ['1月', '2月', '4月', '5月', '6月', '7月']

    result = {
        "status": True,
        "data": {
            "legend": legend,
            "series_list": series_list,
            "x_axis": x_axis,
        }
    }

    return JsonResponse(result)


def chart_pie(request):
    """ 构造饼图的数据"""

    db_data_list = [
        {"value": 2048, "name": 'IT部门'},
        {"value": 1735, "name": '运营'},
        {"value": 580, "name": '新媒体'},
    ]

    result = {
        "status": True,
        "data": db_data_list,
    }
    return JsonResponse(result)


def chart_line(request):
    legend = ["河北", "上海"]

    series_list = [
        {
            "name": '河北',
            "type": 'line',
            "stack": 'Total',
            "data": [15, 20, 36, 10, 10, 100]
        },
        {
            "name": '上海',
            "type": 'line',
            "stack": 'Total',
            "data": [30, 40, 66, 20, 20, 100]
        }
    ]

    x_axis = ['1月', '2月', '4月', '5月', '6月', '7月']

    result = {
        "status": True,
        "data": {
            "legend": legend,
            "series_list": series_list,
            "x_axis": x_axis,
        }
    }

    return JsonResponse(result)


def chart_highcharts(request):
    """ highcharts实例"""
    return render(request, "highcharts.html")

app01/templates/error.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="alert alert-danger" role="alert">{{ msg }}</div>
    </div>
{% endblock content %}

app01/templates/order_list.html
{% extends 'layout.html' %}

{% block css %}
    <style>
        table, th, td {
            text-align: center;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 20px">
            <input type="button" value="新建订单1" class="btn btn-success" data-toggle="modal" data-target="#myModal">
            <input type="button" id="btnAdd" value="新建订单2" class="btn btn-success">
        </div>

        <!-- 面板-->
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                订单列表
            </div>

            <!-- Table -->
            <table class="table table-bordered table-striped table-hover">
                <thead>
                <tr>
                    <th>序号</th>
                    <th>ID</th>
                    <th>订单号</th>
                    <th>名称</th>
                    <th>价格</th>
                    <th>状态</th>
                    <th>管理员</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr uid="{{ obj.id }}">
                        <td>{{ forloop.revcounter }}</td>
                        <td>{{ obj.id }}</td>
                        <td>{{ obj.oid }}</td>
                        <td>{{ obj.title }}</td>
                        <td>{{ obj.price }}</td>
                        <td>{{ obj.get_status_display }}</td>
                        <td>{{ obj.admin.username }}</td>
                        <td>
                            <input uid="{{ obj.id }}" type="button" class="btn btn-primary btn-xs btn-edit" value="编辑">
                            <input uid="{{ obj.id }}" type="button" class="btn btn-danger btn-xs btn-delete" value="删除">
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        {# 分页 #}
        <ul class='pagination'>
            {{ page_string }}
        </ul>
    </div>

    <!-- 新建/编辑 订单（对话框） -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">新建</h4>
                </div>
                <div class="modal-body">
                    <form id="formAdd">

                        <div class="clearfix">
                            {% for obj in form %}
                                <div class="col-xs-6">
                                    <div class="form-group" style="position: relative;margin-bottom: 20px">
                                        <label>{{ obj.label }}</label>
                                        {{ obj }}
                                        <span class="error-msg" style="color: red;position: absolute"></span>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>


                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关 闭</button>
                    <button id="btnSave" type="button" class="btn btn-primary">保 存</button>
                </div>
            </div>
        </div>
    </div>

    <!-- 删除 对话框-->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="alert alert-danger alert-dismissible fade in" role="alert">
                <h4>是否确定要删除？</h4>
                <p style="padding: 10px 0">删除后，所有相关联的数据都将被删除。</p>
                <p style="text-align: right">
                    <button id="btnConfirmDelete" type="button" class="btn btn-danger">确 定</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
                </p>
            </div>
        </div>
    </div>
{% endblock content %}

{% block js %}
    <script type="text/javascript">
        var DELETE_id;
        var EDIT_ID;
        $(function () {
            bindBtnAddEvent();
            bindBtnSaveEvent();
            bindBtnDeleteEvent();
            btnConfirmDeleteEvent();
            btnBtnEditEvent();

        })

        function bindBtnAddEvent() {
            $("#btnAdd").click(function () {
                // 将正在编辑的ID设置为空
                EDIT_ID = undefined;

                // 清空对话框中的数据
                $("#formAdd")[0].reset();

                // 设置对话框的标题
                $("#myModalLabel").text("新建");

                // 点击新建按钮，显示对话框
                $("#myModal").modal("show");
            });
        }

        function bindBtnSaveEvent() {
            $("#btnSave").click(function () {

                // 清除错误信息
                $(".error-msg").empty();

                if (EDIT_ID) {
                    // 编辑
                    doEdit();
                } else {
                    // 添加
                    doAdd();
                }

            });
        }

        function doEdit(){
            // 向后台发送请求 （添加的Ajax请求）
            $.ajax({
                url: "/order/edit/" + "?uid=" + EDIT_ID,
                type: "post",
                data: $("#formAdd").serialize(),
                dataType: "JSON",
                success: function (res) {
                    if (res.status) {
                        // 清空表单 $("#formAdd")是jQuery对象 -> $("#formAdd")[0] DOM对象
                        $("#formAdd")[0].reset();

                        // 关闭对话框
                        $("#myModal").modal('hide');

                        // 刷新页面
                        location.reload()

                    } else {
                        if(res.tips){
                            alert(res.tips);
                        }else {
                           // 把错误信息显示在对话框中
                            console.log(res);
                            $.each(res.error, function (name, errorList) {
                                $("#id_" + name).next().text(errorList[0]);
                            })
                        }

                    }
                }
            })
        }

        function doAdd() {
            // 向后台发送请求 （添加的Ajax请求）
            $.ajax({
                url: "/order/add/",
                type: "post",
                data: $("#formAdd").serialize(),
                dataType: "JSON",
                success: function (res) {
                    if (res.status) {
                        alert("创建成功");
                        // 清空表单 $("#formAdd")是jQuery对象 -> $("#formAdd")[0] DOM对象
                        $("#formAdd")[0].reset();

                        // 关闭对话框
                        $("#myModal").modal('hide');

                        // 刷新页面
                        location.reload()

                    } else {
                        // 把错误信息显示在对话框中
                        console.log(res);
                        $.each(res.error, function (name, errorList) {
                            $("#id_" + name).next().text(errorList[0]);
                        })
                    }
                }
            })
        }

        function bindBtnDeleteEvent() {
            $(".btn-delete").click(function () {
                $("#deleteModal").modal('show')

                // 获取当前当的ID赋值给全局变量
                DELETE_id = $(this).attr("uid");
            })
        }

        function btnConfirmDeleteEvent() {
            $('#btnConfirmDelete').click(function () {
                // 点击确认删除按钮，将全局变量中设置的那个要删除的ID发送到后台
                $.ajax({
                    url: "/order/delete/",
                    type: "GET",
                    data: {
                        uid: DELETE_id,
                    },
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            alert('删除成功');

                            // 隐藏删除框
                            // $("#deleteModal").modal('hide')

                            // 在页面上将当前一行数据删除（js）
                            // $('tr[uid="'+ DELETE_id +'"]').remove();

                            // 全局变量 要删除的id置空
                            //DELETE_id = 0;

                            // 简单的思路，删除完刷新页面
                            location.reload();
                        } else {
                            // 删除失败
                            alert(res.error)
                        }
                    }
                })
            })
        }

        function btnBtnEditEvent() {
            $('.btn-edit').click(function () {
                // 清空对话框中的数据
                $("#formAdd")[0].reset();

                var uid = $(this).attr("uid");
                EDIT_ID = uid;

                // 发送Ajax 去后端获取当前行的相关数据
                $.ajax({
                    url: "/order/detail/",
                    type: "GET",
                    data: {
                        uid: uid,
                    },
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            console.log(res.data);

                            // 将数据赋值到对话框中的标签中
                            $.each(res.data, function (name, value) {
                                $("#id_" + name).val(value);
                            })

                            // 修改对话框的标题
                            $("#myModalLabel").text("编辑");

                            // 点击编辑，显示对话框
                            $("#myModal").modal("show");

                        } else {
                            alert(res.error);
                        }
                    }
                })
            })
        }
    </script>
{% endblock js %}

app01/templates/task_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                添加任务
            </div>
            <div class="panel-body">

                <form id="formAdd">

                    <div class="clearfix">
                        {% for obj in form %}
                            <div class="col-xs-6">
                                <div class="form-group" style="position: relative;margin-bottom: 20px">
                                    <label>{{ obj.label }}</label>
                                    {{ obj }}
                                    <span class="error-msg" style="color: red;position: absolute"></span>
                                </div>
                            </div>
                        {% endfor %}
                    </div >

                    <div class="col-xs-12">
                        <button id="btnAdd" type="button" class="btn btn-primary">提 交</button>
                    </div>
                </form>
            </div>
        </div>

        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                任务列表
            </div>

            <!-- Table -->
            <table class="table table-bordered table-striped table-hover">
                <thead>
                <tr>
                    <th>序号</th>
                    <th>ID</th>
                    <th>标题</th>
                    <th>级别</th>
                    <th>负责人</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <th>{{ forloop.counter }}</th>
                        <td>{{ obj.id }}</td>
                        <td>{{ obj.title }}</td>
                        <td>{{ obj.get_level_display }}</td>
                        <td>{{ obj.user.username }}</td>
                        <td>
                            <a href="/admin/{{ obj.id }}/edit" class="btn btn-primary btn-xs">编辑</a>
                            <a href="/admin/{{ obj.id }}/delete" class="btn btn-danger btn-xs">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <ul class='pagination'>
            {{ page_string }}
        </ul>
    </div>
{% endblock content %}

{% block js %}
    <script type="text/javascript">
        $(function (){
            // 页面框架加载完成之后代码自动执行
            bindBtnAddEvent();
        })

        function bindBtnAddEvent(){
            $("#btnAdd").click(function (){
                $(".error-msg").empty();

                $.ajax({
                    url: '/task/add/',
                    type: "post",
                    data: $("#formAdd").serialize(),
                    dataType: "JSON",
                    success: function (res){
                        if (res.status){
                            alert("添加成功");
                            // 用JS实现页面的刷新
                            location.reload();
                        }else {
                            $.each(res.error, function (name,data){
                                $("#id_" + name).next().text(data[0])
                            })
                        }
                    }
                })
            })
        }
    </script>
{% endblock js %}